export enum Quality {
    FourStar,
    FiveStar
}

export enum Element {
    Anemo = "anemo",
    Geo = "geo",
    Electro = "electro",
    Dendro = "dendro",
    Hydro = "hydro",
    Pyro = "pyro",
    Cryo = "cryo",
    Unaligned = "unaligned",
}

export enum Weapon {
    Sword = "sword",
    Claymore = "claymore",
    Polearm = "polearm",
    Bow = "bow",
    Catalyst = "catalyst"
}

export enum Region {
    Mondstadt,
    Liyue,
    Inazuma,
    Sumeru,
    Fontaine,
    Natlan,
    Snezhnaya,
    NodKrai,
    OtherWorld
}

export enum Model {
    ShortFemale,
    MediumFemale,
    TallFemale,
    MediumMale,
    TallMale
}

export type Character = {
    id: string;
    name: string;
    shortName?: string;
    icon?: string;
    quality: Quality;
    element: Element;
    weapon: Weapon;
    region: Region;
    model: Model;
    release: string;
    version: string;
}

export const DATA: Character[] = [
    {
        "id": "aether",
        "name": "Aether",
        "quality": Quality.FiveStar,
        "element": Element.Unaligned,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "aino",
        "name": "Aino",
        "quality": Quality.FourStar,
        "element": Element.Hydro,
        "weapon": Weapon.Claymore,
        "region": Region.NodKrai,
        "model": Model.ShortFemale,
        "release": "2025-09-10T00:00:00.000Z",
        "version": "Luna I"
    },
    {
        "id": "albedo",
        "name": "Albedo",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Sword,
        "region": Region.Mondstadt,
        "model": Model.MediumMale,
        "release": "2020-12-23T00:00:00.000Z",
        "version": "1.2"
    },
    {
        "id": "alhaitham",
        "name": "Alhaitham",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Sword,
        "region": Region.Sumeru,
        "model": Model.TallMale,
        "release": "2023-01-18T00:00:00.000Z",
        "version": "3.4"
    },
    {
        "id": "aloy",
        "name": "Aloy",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Bow,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "2021-09-01T00:00:00.000Z",
        "version": "2.1"
    },
    {
        "id": "amber",
        "name": "Amber",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Bow,
        "region": Region.Mondstadt,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "arataki_itto",
        "name": "Arataki Itto",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Claymore,
        "region": Region.Inazuma,
        "model": Model.TallMale,
        "release": "2021-12-14T00:00:00.000Z",
        "version": "2.3"
    },
    {
        "id": "arlecchino",
        "name": "Arlecchino",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Polearm,
        "region": Region.Snezhnaya,
        "model": Model.TallFemale,
        "release": "2024-04-24T00:00:00.000Z",
        "version": "4.6"
    },
    {
        "id": "baizhu",
        "name": "Baizhu",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Catalyst,
        "region": Region.Liyue,
        "model": Model.TallMale,
        "release": "2023-05-02T00:00:00.000Z",
        "version": "3.6"
    },
    {
        "id": "barbara",
        "name": "Barbara",
        "quality": Quality.FourStar,
        "element": Element.Hydro,
        "weapon": Weapon.Catalyst,
        "region": Region.Mondstadt,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "beidou",
        "name": "Beidou",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Claymore,
        "region": Region.Liyue,
        "model": Model.TallFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "bennett",
        "name": "Bennett",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Sword,
        "region": Region.Mondstadt,
        "model": Model.MediumMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "candace",
        "name": "Candace",
        "quality": Quality.FourStar,
        "element": Element.Hydro,
        "weapon": Weapon.Polearm,
        "region": Region.Sumeru,
        "model": Model.TallFemale,
        "release": "2022-09-28T00:00:00.000Z",
        "version": "3.1"
    },
    {
        "id": "charlotte",
        "name": "Charlotte",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Catalyst,
        "region": Region.Fontaine,
        "model": Model.MediumFemale,
        "release": "2023-11-08T00:00:00.000Z",
        "version": "4.2"
    },
    {
        "id": "chasca",
        "name": "Chasca",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Bow,
        "region": Region.Natlan,
        "model": Model.TallFemale,
        "release": "2024-11-20T00:00:00.000Z",
        "version": "5.2"
    },
    {
        "id": "chevreuse",
        "name": "Chevreuse",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Polearm,
        "region": Region.Fontaine,
        "model": Model.MediumFemale,
        "release": "2024-01-09T00:00:00.000Z",
        "version": "4.3"
    },
    {
        "id": "chiori",
        "name": "Chiori",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Sword,
        "region": Region.Inazuma,
        "model": Model.MediumFemale,
        "release": "2024-03-13T00:00:00.000Z",
        "version": "4.5"
    },
    {
        "id": "chongyun",
        "name": "Chongyun",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Claymore,
        "region": Region.Liyue,
        "model": Model.MediumMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "citlali",
        "name": "Citlali",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Catalyst,
        "region": Region.Natlan,
        "model": Model.MediumFemale,
        "release": "2025-01-01T00:00:00.000Z",
        "version": "5.3"
    },
    {
        "id": "clorinde",
        "name": "Clorinde",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Sword,
        "region": Region.Fontaine,
        "model": Model.TallFemale,
        "release": "2024-06-05T00:00:00.000Z",
        "version": "4.7"
    },
    {
        "id": "collei",
        "name": "Collei",
        "quality": Quality.FourStar,
        "element": Element.Dendro,
        "weapon": Weapon.Bow,
        "region": Region.Sumeru,
        "model": Model.MediumFemale,
        "release": "2022-08-24T00:00:00.000Z",
        "version": "3.0"
    },
    {
        "id": "cyno",
        "name": "Cyno",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Polearm,
        "region": Region.Sumeru,
        "model": Model.MediumMale,
        "release": "2022-09-28T00:00:00.000Z",
        "version": "3.1"
    },
    {
        "id": "dahlia",
        "name": "Dahlia",
        "quality": Quality.FourStar,
        "element": Element.Hydro,
        "weapon": Weapon.Sword,
        "region": Region.Mondstadt,
        "model": Model.MediumMale,
        "release": "2025-06-18T00:00:00.000Z",
        "version": "5.7"
    },
    {
        "id": "dehya",
        "name": "Dehya",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Claymore,
        "region": Region.Sumeru,
        "model": Model.TallFemale,
        "release": "2023-03-01T00:00:00.000Z",
        "version": "3.5"
    },
    {
        "id": "diluc",
        "name": "Diluc",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Claymore,
        "region": Region.Mondstadt,
        "model": Model.TallMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "diona",
        "name": "Diona",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Bow,
        "region": Region.Mondstadt,
        "model": Model.ShortFemale,
        "release": "2020-11-11T00:00:00.000Z",
        "version": "1.1"
    },
    {
        "id": "dori",
        "name": "Dori",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Claymore,
        "region": Region.Sumeru,
        "model": Model.ShortFemale,
        "release": "2022-09-09T00:00:00.000Z",
        "version": "3.0"
    },
    {
        "id": "durin",
        "name": "Durin",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Sword,
        "region": Region.Mondstadt,
        "model": Model.MediumMale,
        "release": "2025-12-03T00:00:00.000Z",
        "version": "6.2"
    },
    {
        "id": "emilie",
        "name": "Emilie",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Polearm,
        "region": Region.Fontaine,
        "model": Model.MediumFemale,
        "release": "2024-08-06T00:00:00.000Z",
        "version": "4.8"
    },
    {
        "id": "escoffier",
        "name": "Escoffier",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Polearm,
        "region": Region.Fontaine,
        "model": Model.MediumFemale,
        "release": "2025-05-07T00:00:00.000Z",
        "version": "5.6"
    },
    {
        "id": "eula",
        "name": "Eula",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Claymore,
        "region": Region.Mondstadt,
        "model": Model.TallFemale,
        "release": "2021-05-18T00:00:00.000Z",
        "version": "1.5"
    },
    {
        "id": "faruzan",
        "name": "Faruzan",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Bow,
        "region": Region.Sumeru,
        "model": Model.MediumFemale,
        "release": "2022-12-07T00:00:00.000Z",
        "version": "3.3"
    },
    {
        "id": "fischl",
        "name": "Fischl",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Bow,
        "region": Region.Mondstadt,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "flins",
        "name": "Flins",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Polearm,
        "region": Region.NodKrai,
        "model": Model.TallMale,
        "release": "2025-09-10T00:00:00.000Z",
        "version": "6.0"
    },
    {
        "id": "freminet",
        "name": "Freminet",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Claymore,
        "region": Region.Fontaine,
        "model": Model.MediumMale,
        "release": "2023-09-05T00:00:00.000Z",
        "version": "4.0"
    },
    {
        "id": "furina",
        "name": "Furina",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Sword,
        "region": Region.Fontaine,
        "model": Model.MediumFemale,
        "release": "2023-11-08T00:00:00.000Z",
        "version": "4.2"
    },
    {
        "id": "gaming",
        "name": "Gaming",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Claymore,
        "region": Region.Liyue,
        "model": Model.MediumMale,
        "release": "2024-01-31T00:00:00.000Z",
        "version": "4.4"
    },
    {
        "id": "ganyu",
        "name": "Ganyu",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Bow,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2021-01-12T00:00:00.000Z",
        "version": "1.2"
    },
    {
        "id": "gorou",
        "name": "Gorou",
        "quality": Quality.FourStar,
        "element": Element.Geo,
        "weapon": Weapon.Bow,
        "region": Region.Inazuma,
        "model": Model.MediumMale,
        "release": "2021-12-14T00:00:00.000Z",
        "version": "2.3"
    },
    {
        "id": "hu_tao",
        "name": "Hu Tao",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Polearm,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2021-03-02T00:00:00.000Z",
        "version": "1.3"
    },
    {
        "id": "iansan",
        "name": "Iansan",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Polearm,
        "region": Region.Natlan,
        "model": Model.ShortFemale,
        "release": "2025-03-26T00:00:00.000Z",
        "version": "5.5"
    },
    {
        "id": "ifa",
        "name": "Ifa",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Catalyst,
        "region": Region.Natlan,
        "model": Model.TallMale,
        "release": "2025-05-07T00:00:00.000Z",
        "version": "5.6"
    },
    {
        "id": "ineffa",
        "name": "Ineffa",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Polearm,
        "region": Region.NodKrai,
        "model": Model.MediumFemale,
        "release": "2025-07-30T00:00:00.000Z",
        "version": "5.8"
    },
    {
        "id": "jahoda",
        "name": "Jahoda",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Bow,
        "region": Region.NodKrai,
        "model": Model.MediumFemale,
        "release": "2025-12-03T00:00:00.000Z",
        "version": "6.2"
    },
    {
        "id": "jean",
        "name": "Jean",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Sword,
        "region": Region.Mondstadt,
        "model": Model.TallFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "kachina",
        "name": "Kachina",
        "quality": Quality.FourStar,
        "element": Element.Geo,
        "weapon": Weapon.Polearm,
        "region": Region.Natlan,
        "model": Model.ShortFemale,
        "release": "2024-08-28T00:00:00.000Z",
        "version": "5.0"
    },
    {
        "id": "kaedehara_kazuha",
        "name": "Kaedehara Kazuha",
        shortName: "Kazuha",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Sword,
        "region": Region.Inazuma,
        "model": Model.MediumMale,
        "release": "2021-06-29T00:00:00.000Z",
        "version": "1.6"
    },
    {
        "id": "kaeya",
        "name": "Kaeya",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Sword,
        "region": Region.Mondstadt,
        "model": Model.TallMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "kamisato_ayaka",
        "name": "Kamisato Ayaka",
        shortName: "Ayaka",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Sword,
        "region": Region.Inazuma,
        "model": Model.MediumFemale,
        "release": "2021-07-21T00:00:00.000Z",
        "version": "2.0"
    },
    {
        "id": "kamisato_ayato",
        "name": "Kamisato Ayato",
        shortName: "Ayato",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Sword,
        "region": Region.Inazuma,
        "model": Model.TallMale,
        "release": "2022-03-30T00:00:00.000Z",
        "version": "2.6"
    },
    {
        "id": "kaveh",
        "name": "Kaveh",
        "quality": Quality.FourStar,
        "element": Element.Dendro,
        "weapon": Weapon.Claymore,
        "region": Region.Sumeru,
        "model": Model.TallMale,
        "release": "2023-05-02T00:00:00.000Z",
        "version": "3.6"
    },
    {
        "id": "keqing",
        "name": "Keqing",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Sword,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "kinich",
        "name": "Kinich",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Claymore,
        "region": Region.Natlan,
        "model": Model.MediumMale,
        "release": "2024-09-17T00:00:00.000Z",
        "version": "5.0"
    },
    {
        "id": "kirara",
        "name": "Kirara",
        "quality": Quality.FourStar,
        "element": Element.Dendro,
        "weapon": Weapon.Sword,
        "region": Region.Inazuma,
        "model": Model.MediumFemale,
        "release": "2023-05-24T00:00:00.000Z",
        "version": "3.7"
    },
    {
        "id": "klee",
        "name": "Klee",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Catalyst,
        "region": Region.Mondstadt,
        "model": Model.ShortFemale,
        "release": "2020-10-20T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "kujou_sara",
        "name": "Kujou Sara",
        shortName: "Sara",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Bow,
        "region": Region.Inazuma,
        "model": Model.TallFemale,
        "release": "2021-09-01T00:00:00.000Z",
        "version": "2.1"
    },
    {
        "id": "kuki_shinobu",
        "name": "Kuki Shinobu",
        shortName: "Shinobu",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Sword,
        "region": Region.Inazuma,
        "model": Model.MediumFemale,
        "release": "2022-06-21T00:00:00.000Z",
        "version": "2.7"
    },
    {
        "id": "lan_yan",
        "name": "Lan Yan",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Catalyst,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2025-01-21T00:00:00.000Z",
        "version": "5.3"
    },
    {
        "id": "lauma",
        "name": "Lauma",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Catalyst,
        "region": Region.NodKrai,
        "model": Model.TallFemale,
        "release": "2025-09-10T00:00:00.000Z",
        "version": "Luna I"
    },
    {
        "id": "layla",
        "name": "Layla",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Sword,
        "region": Region.Sumeru,
        "model": Model.MediumFemale,
        "release": "2022-11-18T00:00:00.000Z",
        "version": "3.2"
    },
    {
        "id": "lisa",
        "name": "Lisa",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Catalyst,
        "region": Region.Mondstadt,
        "model": Model.TallFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "lumine",
        "name": "Lumine",
        "quality": Quality.FiveStar,
        "element": Element.Unaligned,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "lynette",
        "name": "Lynette",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Sword,
        "region": Region.Fontaine,
        "model": Model.MediumFemale,
        "release": "2023-08-16T00:00:00.000Z",
        "version": "4.0"
    },
    {
        "id": "lyney",
        "name": "Lyney",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Bow,
        "region": Region.Fontaine,
        "model": Model.MediumMale,
        "release": "2023-08-16T00:00:00.000Z",
        "version": "4.0"
    },
    {
        "id": "mavuika",
        "name": "Mavuika",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Claymore,
        "region": Region.Natlan,
        "model": Model.TallFemale,
        "release": "2025-01-01T00:00:00.000Z",
        "version": "5.3"
    },
    {
        "id": "mika",
        "name": "Mika",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Polearm,
        "region": Region.Mondstadt,
        "model": Model.MediumMale,
        "release": "2023-03-21T00:00:00.000Z",
        "version": "3.5"
    },
    {
        "id": "mona",
        "name": "Mona",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Catalyst,
        "region": Region.Mondstadt,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "mualani",
        "name": "Mualani",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Catalyst,
        "region": Region.Natlan,
        "model": Model.MediumFemale,
        "release": "2024-08-28T00:00:00.000Z",
        "version": "5.0"
    },
    {
        "id": "nahida",
        "name": "Nahida",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Catalyst,
        "region": Region.Sumeru,
        "model": Model.ShortFemale,
        "release": "2022-11-02T00:00:00.000Z",
        "version": "3.2"
    },
    {
        "id": "navia",
        "name": "Navia",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Claymore,
        "region": Region.Fontaine,
        "model": Model.TallFemale,
        "release": "2023-12-20T00:00:00.000Z",
        "version": "4.3"
    },
    {
        "id": "nefer",
        "name": "Nefer",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Catalyst,
        "region": Region.NodKrai,
        "model": Model.TallFemale,
        "release": "2025-10-22T00:00:00.000Z",
        "version": "6.1"
    },
    {
        "id": "neuvillette",
        "name": "Neuvillette",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Catalyst,
        "region": Region.Fontaine,
        "model": Model.TallMale,
        "release": "2023-09-27T00:00:00.000Z",
        "version": "4.1"
    },
    {
        "id": "nilou",
        "name": "Nilou",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Sword,
        "region": Region.Sumeru,
        "model": Model.MediumFemale,
        "release": "2022-10-14T00:00:00.000Z",
        "version": "3.1"
    },
    {
        "id": "ningguang",
        "name": "Ningguang",
        "quality": Quality.FourStar,
        "element": Element.Geo,
        "weapon": Weapon.Catalyst,
        "region": Region.Liyue,
        "model": Model.TallFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "noelle",
        "name": "Noelle",
        "quality": Quality.FourStar,
        "element": Element.Geo,
        "weapon": Weapon.Claymore,
        "region": Region.Mondstadt,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "ororon",
        "name": "Ororon",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Bow,
        "region": Region.Natlan,
        "model": Model.TallMale,
        "release": "2024-11-20T00:00:00.000Z",
        "version": "5.2"
    },
    {
        "id": "qiqi",
        "name": "Qiqi",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Sword,
        "region": Region.Liyue,
        "model": Model.ShortFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "raiden_shogun",
        "name": "Raiden Shogun",
        shortName: "Shogun",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Polearm,
        "region": Region.Inazuma,
        "model": Model.TallFemale,
        "release": "2021-09-01T00:00:00.000Z",
        "version": "2.1"
    },
    {
        "id": "razor",
        "name": "Razor",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Claymore,
        "region": Region.Mondstadt,
        "model": Model.MediumMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "rosaria",
        "name": "Rosaria",
        "quality": Quality.FourStar,
        "element": Element.Cryo,
        "weapon": Weapon.Polearm,
        "region": Region.Mondstadt,
        "model": Model.TallFemale,
        "release": "2021-04-06T00:00:00.000Z",
        "version": "1.4"
    },
    {
        "id": "sangonomiya_kokomi",
        "name": "Sangonomiya Kokomi",
        "shortName": "Kokomi",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Catalyst,
        "region": Region.Inazuma,
        "model": Model.MediumFemale,
        "release": "2021-09-21T00:00:00.000Z",
        "version": "2.1"
    },
    {
        "id": "sayu",
        "name": "Sayu",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Claymore,
        "region": Region.Inazuma,
        "model": Model.ShortFemale,
        "release": "2021-08-10T00:00:00.000Z",
        "version": "2.0"
    },
    {
        "id": "sethos",
        "name": "Sethos",
        "quality": Quality.FourStar,
        "element": Element.Electro,
        "weapon": Weapon.Bow,
        "region": Region.Sumeru,
        "model": Model.MediumMale,
        "release": "2024-06-05T00:00:00.000Z",
        "version": "4.7"
    },
    {
        "id": "shenhe",
        "name": "Shenhe",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Polearm,
        "region": Region.Liyue,
        "model": Model.TallFemale,
        "release": "2022-01-05T00:00:00.000Z",
        "version": "2.4"
    },
    {
        "id": "shikanoin_heizou",
        "name": "Shikanoin Heizou",
        shortName: "Heizou",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Catalyst,
        "region": Region.Inazuma,
        "model": Model.MediumMale,
        "release": "2022-07-13T00:00:00.000Z",
        "version": "2.8"
    },
    {
        "id": "sigewinne",
        "name": "Sigewinne",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Bow,
        "region": Region.Fontaine,
        "model": Model.ShortFemale,
        "release": "2024-06-25T00:00:00.000Z",
        "version": "4.7"
    },
    {
        "id": "skirk",
        "name": "Skirk",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "2025-06-18T00:00:00.000Z",
        "version": "5.7"
    },
    {
        "id": "sucrose",
        "name": "Sucrose",
        "quality": Quality.FourStar,
        "element": Element.Anemo,
        "weapon": Weapon.Catalyst,
        "region": Region.Mondstadt,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "tartaglia",
        "name": "Tartaglia",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Bow,
        "region": Region.Snezhnaya,
        "model": Model.TallMale,
        "release": "2020-11-11T00:00:00.000Z",
        "version": "1.1"
    },
    {
        "id": "thoma",
        "name": "Thoma",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Polearm,
        "region": Region.Inazuma,
        "model": Model.TallMale,
        "release": "2021-11-02T00:00:00.000Z",
        "version": "2.2"
    },
    {
        "id": "tighnari",
        "name": "Tighnari",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Bow,
        "region": Region.Sumeru,
        "model": Model.MediumMale,
        "release": "2022-08-24T00:00:00.000Z",
        "version": "3.0"
    },
    {
        "id": "traveler_anemo_aether",
        "name": "Traveler (Anemo Aether)",
        shortName: "Aether",
        icon: "aether",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumMale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_geo_aether",
        "name": "Traveler (Geo Aether)",
        shortName: "Aether",
        icon: "aether",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumMale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_electro_aether",
        "name": "Traveler (Electro Aether)",
        shortName: "Aether",
        icon: "aether",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumMale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_dendro_aether",
        "name": "Traveler (Dendro Aether)",
        shortName: "Aether",
        icon: "aether",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumMale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_hydro_aether",
        "name": "Traveler (Hydro Aether)",
        shortName: "Aether",
        icon: "aether",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumMale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_pyro_aether",
        "name": "Traveler (Pyro Aether)",
        shortName: "Aether",
        icon: "aether",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumMale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_anemo_lumine",
        "name": "Traveler (Anemo Lumine)",
        shortName: "Lumine",
        icon: "lumine",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_geo_lumine",
        "name": "Traveler (Geo Lumine)",
        shortName: "Lumine",
        icon: "lumine",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_electro_lumine",
        "name": "Traveler (Electro Lumine)",
        shortName: "Lumine",
        icon: "lumine",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_dendro_lumine",
        "name": "Traveler (Dendro Lumine)",
        shortName: "Lumine",
        icon: "lumine",
        "quality": Quality.FiveStar,
        "element": Element.Dendro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_hydro_lumine",
        "name": "Traveler (Hydro Lumine)",
        shortName: "Lumine",
        icon: "lumine",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "",
        "version": ""
    },
    {
        "id": "traveler_pyro_lumine",
        "name": "Traveler (Pyro Lumine)",
        shortName: "Lumine",
        icon: "lumine",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Sword,
        "region": Region.OtherWorld,
        "model": Model.MediumFemale,
        "release": "",
        "version": ""
    },
    {
        "id": "varesa",
        "name": "Varesa",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Catalyst,
        "region": Region.Natlan,
        "model": Model.MediumFemale,
        "release": "2025-03-26T00:00:00.000Z",
        "version": "5.5"
    },
    {
        "id": "venti",
        "name": "Venti",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Bow,
        "region": Region.Mondstadt,
        "model": Model.MediumMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "wanderer",
        "name": "Wanderer",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Catalyst,
        "region": Region.Sumeru,
        "model": Model.MediumMale,
        "release": "2022-12-07T00:00:00.000Z",
        "version": "3.3"
    },
    {
        "id": "wriothesley",
        "name": "Wriothesley",
        "quality": Quality.FiveStar,
        "element": Element.Cryo,
        "weapon": Weapon.Catalyst,
        "region": Region.Fontaine,
        "model": Model.TallMale,
        "release": "2023-10-17T00:00:00.000Z",
        "version": "4.1"
    },
    {
        "id": "xiangling",
        "name": "Xiangling",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Polearm,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "xianyun",
        "name": "Xianyun",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Catalyst,
        "region": Region.Liyue,
        "model": Model.TallFemale,
        "release": "2024-01-31T00:00:00.000Z",
        "version": "4.4"
    },
    {
        "id": "xiao",
        "name": "Xiao",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Polearm,
        "region": Region.Liyue,
        "model": Model.MediumMale,
        "release": "2021-02-03T00:00:00.000Z",
        "version": "1.3"
    },
    {
        "id": "xilonen",
        "name": "Xilonen",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Sword,
        "region": Region.Natlan,
        "model": Model.TallFemale,
        "release": "2024-10-09T00:00:00.000Z",
        "version": "5.1"
    },
    {
        "id": "xingqiu",
        "name": "Xingqiu",
        "quality": Quality.FourStar,
        "element": Element.Hydro,
        "weapon": Weapon.Sword,
        "region": Region.Liyue,
        "model": Model.MediumMale,
        "release": "2020-09-28T00:00:00.000Z",
        "version": "1.0"
    },
    {
        "id": "xinyan",
        "name": "Xinyan",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Claymore,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2020-12-01T00:00:00.000Z",
        "version": "1.1"
    },
    {
        "id": "yae_miko",
        "name": "Yae Miko",
        "quality": Quality.FiveStar,
        "element": Element.Electro,
        "weapon": Weapon.Catalyst,
        "region": Region.Inazuma,
        "model": Model.TallFemale,
        "release": "2022-02-16T00:00:00.000Z",
        "version": "2.5"
    },
    {
        "id": "yanfei",
        "name": "Yanfei",
        "quality": Quality.FourStar,
        "element": Element.Pyro,
        "weapon": Weapon.Catalyst,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2021-04-28T00:00:00.000Z",
        "version": "1.5"
    },
    {
        "id": "yaoyao",
        "name": "Yaoyao",
        "quality": Quality.FourStar,
        "element": Element.Dendro,
        "weapon": Weapon.Polearm,
        "region": Region.Liyue,
        "model": Model.ShortFemale,
        "release": "2023-01-18T00:00:00.000Z",
        "version": "3.4"
    },
    {
        "id": "yelan",
        "name": "Yelan",
        "quality": Quality.FiveStar,
        "element": Element.Hydro,
        "weapon": Weapon.Bow,
        "region": Region.Liyue,
        "model": Model.TallFemale,
        "release": "2022-05-31T00:00:00.000Z",
        "version": "2.7"
    },
    {
        "id": "yoimiya",
        "name": "Yoimiya",
        "quality": Quality.FiveStar,
        "element": Element.Pyro,
        "weapon": Weapon.Bow,
        "region": Region.Inazuma,
        "model": Model.MediumFemale,
        "release": "2021-08-10T00:00:00.000Z",
        "version": "2.0"
    },
    {
        "id": "yumemizuki_mizuki",
        "name": "Yumemizuki Mizuki",
        shortName: "Mizuki",
        "quality": Quality.FiveStar,
        "element": Element.Anemo,
        "weapon": Weapon.Catalyst,
        "region": Region.Inazuma,
        "model": Model.MediumFemale,
        "release": "2025-02-12T00:00:00.000Z",
        "version": "5.4"
    },
    {
        "id": "yun_jin",
        "name": "Yun Jin",
        "quality": Quality.FourStar,
        "element": Element.Geo,
        "weapon": Weapon.Polearm,
        "region": Region.Liyue,
        "model": Model.MediumFemale,
        "release": "2022-01-05T00:00:00.000Z",
        "version": "2.4"
    },
    {
        "id": "zhongli",
        "name": "Zhongli",
        "quality": Quality.FiveStar,
        "element": Element.Geo,
        "weapon": Weapon.Polearm,
        "region": Region.Liyue,
        "model": Model.TallMale,
        "release": "2020-12-01T00:00:00.000Z",
        "version": "1.1"
    }
]
